<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Views\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Sdl.MultiSelectComboBox" Version="1.0.103" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Character.Core\Character.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="Styles\MultiSelectComboBox.Custom.ControlTemplate.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>XamlIntelliSenseFileGenerator</Generator>
    </Page>
    <Page Update="Styles\MultiSelectComboBox.Custom.DropdownItemTemplate.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>XamlIntelliSenseFileGenerator</Generator>
    </Page>
    <Page Update="Styles\MultiSelectComboBox.Custom.Image.Resources.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>XamlIntelliSenseFileGenerator</Generator>
    </Page>
    <Page Update="Styles\MultiSelectComboBox.Custom.SelectedItemTemplate.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>XamlIntelliSenseFileGenerator</Generator>
    </Page>
    <Page Update="Styles\MultiSelectComboBox.Custom.Tooltip.Resources.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>XamlIntelliSenseFileGenerator</Generator>
    </Page>
    <Page Update="Styles\MultiSelectComboBox.Resources.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>XamlIntelliSenseFileGenerator</Generator>
    </Page>
  </ItemGroup>

</Project>
