<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationIcon>Images\Logo.ico</ApplicationIcon>
	<BuildTimeUtc>$([System.DateTime]::UtcNow.ToString("o"))</BuildTimeUtc>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\DataEditor\Gold_OffC.ico" />
    <None Remove="Images\DataEditor\Gold_OffS.ico" />
    <None Remove="Images\DataEditor\Gold_OnC.ico" />
    <None Remove="Images\DataEditor\Gold_OnS.ico" />
    <None Remove="Images\Logo.ico" />
    <None Remove="Images\Manager\Genesys.ico" />
    <None Remove="Images\Manager\Rarity.ico" />
    <None Remove="Images\Settings\Setting.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="HighLight\Blue.xshd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="HighLight\DarkGreen.xshd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="HighLight\DarkPure.xshd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="HighLight\DarkRed.xshd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="HighLight\Default.xshd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="HighLight\Indigo.xshd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="HighLight\Purple.xshd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="Images\DataEditor\Gold_OffC.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\DataEditor\Gold_OffS.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\DataEditor\Gold_OnC.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\DataEditor\Gold_OnS.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\DataEditor\RightScale.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Content Include="Images\Message\Error.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Message\Information.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Message\Notification.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Message\Question.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Message\Warning.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
    <PackageReference Include="Dirkster.AvalonDock.Themes.VS2013" Version="4.72.1" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="11.0.0-preview.2.26159.112" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageReference Include="Sdl.MultiSelectComboBox" Version="1.0.103" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.118" />
    <PackageReference Include="WindowsAPICodePack" Version="8.0.14" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
        <_Parameter1>BuildTimeUtc</_Parameter1>
        <_Parameter2>$(BuildTimeUtc)</_Parameter2>
    </AssemblyAttribute>
    
    <Content Include="Images\Blank.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    
    <ProjectReference Include="..\Character.Core\Character.Core.csproj" />
    <ProjectReference Include="..\Scrapiyard.Converter\Scrapiyard.Converter.csproj" />
    <ProjectReference Include="..\Scrapiyard.Core\Scrapiyard.Core.csproj" />
    <Resource Include="Images\Creator.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\DataEditor\Default.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\DataEditor\LeftScale.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\DataEditor\LevelRank.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\DataEditor\Level.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\DataEditor\Link.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\DataEditor\MinusLevel.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\DataEditor\Rank.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Loading.gif">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Logo.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Manager\Genesys.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Manager\Rarity.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Settings\Setting.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Styles\ComboBoxStyles.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      <Generator>XamlIntelliSenseFileGenerator</Generator>
    </Page>
    <Page Update="Styles\MultiSelectComboBox.Custom.ControlTemplate.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>XamlIntelliSenseFileGenerator</Generator>
    </Page>
    <Page Update="Styles\MultiSelectComboBox.Custom.DropdownItemTemplate.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>XamlIntelliSenseFileGenerator</Generator>
    </Page>
    <Page Update="Styles\MultiSelectComboBox.Custom.Image.Resources.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>XamlIntelliSenseFileGenerator</Generator>
    </Page>
    <Page Update="Styles\MultiSelectComboBox.Custom.SelectedItemTemplate.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>XamlIntelliSenseFileGenerator</Generator>
    </Page>
    <Page Update="Styles\MultiSelectComboBox.Custom.Tooltip.Resources.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>XamlIntelliSenseFileGenerator</Generator>
    </Page>
    <Page Update="Styles\MultiSelectComboBox.Resources.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>XamlIntelliSenseFileGenerator</Generator>
    </Page>
    <Page Update="Styles\TriStateToggleStyle.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Debug\net8.0-windows\data\CardData\Images\" />
  </ItemGroup>

</Project>
